// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/administrators/createAdministrator": {
            "post": {
                "description": "coloca os dados do admistrador como name, email  e senha.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "criar admistrador",
                "parameters": [
                    {
                        "description": "Dados da admistrador",
                        "name": "login",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entites.Administrador"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/categories/createCategory": {
            "post": {
                "description": "para realizar o cadastros do engresso precisa name,cpf,data nascimento.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "create engresso",
                "parameters": [
                    {
                        "description": "Dados ebresso",
                        "name": "login",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entites.Engresso"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/dateformulario": {
            "post": {
                "description": "coloca a data de inicio e a data de fim.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Data do tempo de formulari",
                "parameters": [
                    {
                        "description": "Dados da data",
                        "name": "login",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entites.DateFormulario"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/formulario": {
            "post": {
                "description": "Cria um novo formulário com base nos dados fornecidos do engresso.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "formulario"
                ],
                "summary": "Criar um novo formulário",
                "parameters": [
                    {
                        "description": "Dados do formulário a ser criado",
                        "name": "formulario",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entites.Formulario"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/login": {
            "post": {
                "description": "Realiza o login do engresso com cpf e data.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Login do usuário",
                "parameters": [
                    {
                        "description": "Dados de Login",
                        "name": "login",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entites.Loginengresso"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/loginAdm": {
            "post": {
                "description": "Realiza o login do Adm utilizando o email e cpf.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Login do adm",
                "parameters": [
                    {
                        "description": "Dados de Login ADM",
                        "name": "login",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entites.Login"
                        }
                    }
                ],
                "responses": {}
            }
        }
    },
    "definitions": {
        "entites.Administrador": {
            "type": "object",
            "properties": {
                "Password": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "entites.DateFormulario": {
            "type": "object",
            "properties": {
                "date_fim": {
                    "type": "string"
                },
                "date_inicio": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                }
            }
        },
        "entites.Engresso": {
            "type": "object",
            "properties": {
                "cpf": {
                    "type": "string"
                },
                "data_nascimento": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "entites.Formulario": {
            "type": "object",
            "properties": {
                "ano_conclusao_graduacao": {
                    "type": "string"
                },
                "ano_conclusao_pos_graduacao": {
                    "type": "string"
                },
                "ano_inicio_pos_graduacao": {
                    "type": "string"
                },
                "atuacao_docencia": {
                    "type": "boolean"
                },
                "cidade_residencia": {
                    "type": "string"
                },
                "engresso": {
                    "$ref": "#/definitions/entites.Engresso"
                },
                "engresso_id": {
                    "type": "integer"
                },
                "estado_residencia": {
                    "type": "string"
                },
                "faixa_salarial": {
                    "type": "string"
                },
                "genero": {
                    "$ref": "#/definitions/entites.Genero"
                },
                "graduacao_realizada": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "instituicao_trabalho": {
                    "type": "string"
                },
                "linha_pesquisa_pos_graduacao": {
                    "type": "integer"
                },
                "pais_residencia": {
                    "type": "string"
                },
                "ramo": {
                    "type": "string"
                },
                "trabalhando_atualmente": {
                    "type": "boolean"
                }
            }
        },
        "entites.Genero": {
            "type": "string",
            "enum": [
                "Feminino",
                "Masculino",
                "Não-Binário",
                "Não Desejo Informar"
            ],
            "x-enum-varnames": [
                "Feminino",
                "Masculino",
                "NAO_BINARIO",
                "NAO_DESEJO_INFORMAR"
            ]
        },
        "entites.Login": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "entites.Loginengresso": {
            "type": "object",
            "properties": {
                "cpf": {
                    "type": "string"
                },
                "data_nascimento": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BasicAuth": {
            "type": "basic"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Microservices API",
	Description:      "Esta é a documentação da API dos microserviços.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
